# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

encoding:         utf-8

# Setup
title:            LinHung Wei
tagline:          'Human'
description:      'I write things.'
url:              https://adeline-wei.github.io
baseurl:          ''

author:
  name:           'LinHung Wei'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Adeline-Wei

plugins:
  - jekyll-paginate
  - jekyll-gist
